services:
  web:
    image: projector:latest
    build:
      context: .
      dockerfile: Dockerfile.php
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: npm run dev

  database:
    image: postgres
    environment:
        POSTGRES_PASSWORD: root
        POSTGRES_USER: root
    ports:
      - "5432:5432"

volumes:
  node_modules:
