services:
  web:
    image: projector:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile.php
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - vendor:/var/www/html/vendor
    depends_on:
        - database

  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.node
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: npm run dev

  database:
    image: postgres
    environment:
        POSTGRES_PASSWORD: root
        POSTGRES_USER: root
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db_data:/var/lib/postgresql/data
      - ./docker/init_db:/docker-entrypoint-initdb.d
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - database

volumes:
  db-data:
  node_modules:
  vendor:
